### ISSUE TITLE
JS code needs to be in head

### ISSUE THREAD

**Issue by HelloMihai** [MarcelHarabagiu/Todo-list#1]
move JS to head from body.

its bad practice to have JS in the body

line in question:
https://github.com/MarcelHarabagiu/Todo-list/blob/master/index.html#L36

**Comment by MarcelHarabagiu** [comment]
the .js script is now in the head.
the new line:
https://github.com/MarcelHarabagiu/Todo-list/blob/d51ce29d8c94674e36ac3cee57362d5f9b3f3ed1/index.html#L13
