### ISSUE TITLE
missing icons

### ISSUE THREAD

**Issue by HelloMihai** [MarcelHarabagiu/Todo-list#8]
![image](https://user-images.githubusercontent.com/8506019/104644902-3b34d000-5663-11eb-83b2-3d63f533e1a3.png)

delete is missing icons

items loaded from local storage missing completed icon

**Comment by MarcelHarabagiu** [comment]
icon fixed for Mark Button and Trash Button
.classList.add("fas"); 
.classList.add("fa-check");
.classList.add("fa-trash"); 

fixed in both functions: addTodos and getTodos

![image](https://user-images.githubusercontent.com/74360233/104959155-d61a0b00-59d1-11eb-88bf-17fb331e6604.png)
